// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "chatMessage.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface Message ()
+ (Message *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface Device ()
+ (Device *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation Message
+ (Message *)fromMap:(NSDictionary *)dict {
  Message *result = [[Message alloc] init];
  result.text = dict[@"text"];
  if ((NSNull *)result.text == [NSNull null]) {
    result.text = nil;
  }
  result.title = dict[@"title"];
  if ((NSNull *)result.title == [NSNull null]) {
    result.title = nil;
  }
  result.author = dict[@"author"];
  if ((NSNull *)result.author == [NSNull null]) {
    result.author = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.text ? self.text : [NSNull null]), @"text", (self.title ? self.title : [NSNull null]), @"title", (self.author ? self.author : [NSNull null]), @"author", nil];
}
@end

@implementation Device
+ (Device *)fromMap:(NSDictionary *)dict {
  Device *result = [[Device alloc] init];
  result.name = dict[@"name"];
  if ((NSNull *)result.name == [NSNull null]) {
    result.name = nil;
  }
  result.uuids = dict[@"uuids"];
  if ((NSNull *)result.uuids == [NSNull null]) {
    result.uuids = nil;
  }
  result.macAddress = dict[@"macAddress"];
  if ((NSNull *)result.macAddress == [NSNull null]) {
    result.macAddress = nil;
  }
  result.bondState = [dict[@"bondState"] integerValue];
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.name ? self.name : [NSNull null]), @"name", (self.uuids ? self.uuids : [NSNull null]), @"uuids", (self.macAddress ? self.macAddress : [NSNull null]), @"macAddress", @(self.bondState), @"bondState", nil];
}
@end

@interface ChatMessageHostApiCodecReader : FlutterStandardReader
@end
@implementation ChatMessageHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [Device fromMap:[self readValue]];
    
    case 129:     
      return [Message fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface ChatMessageHostApiCodecWriter : FlutterStandardWriter
@end
@implementation ChatMessageHostApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[Device class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[Message class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface ChatMessageHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation ChatMessageHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[ChatMessageHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[ChatMessageHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *ChatMessageHostApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    ChatMessageHostApiCodecReaderWriter *readerWriter = [[ChatMessageHostApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void ChatMessageHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ChatMessageHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.connect"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(connectId:error:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(connectId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = args[0];
        FlutterError *error;
        [api connectId:arg_id error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.disconnect"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disconnectWithError:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(disconnectWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api disconnectWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.sendMessage"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendMessageAuthorId:message:error:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(sendMessageAuthorId:message:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_authorId = args[0];
        Message *arg_message = args[1];
        FlutterError *error;
        [api sendMessageAuthorId:arg_authorId message:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.pairedDevices"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pairedDevicesWithError:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(pairedDevicesWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<Device *> *output = [api pairedDevicesWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.discoverDevices"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(discoverDevicesWithError:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(discoverDevicesWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api discoverDevicesWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.isBluetoothEnabled"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isBluetoothEnabledWithError:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(isBluetoothEnabledWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isBluetoothEnabledWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.isBluetoothAvailable"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isBluetoothAvailableWithError:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(isBluetoothAvailableWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isBluetoothAvailableWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.ChatMessageHostApi.enableBluetooth"
        binaryMessenger:binaryMessenger
        codec:ChatMessageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(enableBluetoothWithError:)], @"ChatMessageHostApi api (%@) doesn't respond to @selector(enableBluetoothWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api enableBluetoothWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface ChatMessageFlutterApiCodecReader : FlutterStandardReader
@end
@implementation ChatMessageFlutterApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [Device fromMap:[self readValue]];
    
    case 129:     
      return [Message fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface ChatMessageFlutterApiCodecWriter : FlutterStandardWriter
@end
@implementation ChatMessageFlutterApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[Device class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[Message class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface ChatMessageFlutterApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation ChatMessageFlutterApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[ChatMessageFlutterApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[ChatMessageFlutterApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *ChatMessageFlutterApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    ChatMessageFlutterApiCodecReaderWriter *readerWriter = [[ChatMessageFlutterApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


@interface ChatMessageFlutterApi ()
@property (nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation ChatMessageFlutterApi
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}

- (void)putMessageMessage:(Message *)arg_message completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.ChatMessageFlutterApi.putMessage"
      binaryMessenger:self.binaryMessenger
      codec:ChatMessageFlutterApiGetCodec()];
  [channel sendMessage:@[arg_message] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)putNewDeviceDevice:(Device *)arg_device completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.ChatMessageFlutterApi.putNewDevice"
      binaryMessenger:self.binaryMessenger
      codec:ChatMessageFlutterApiGetCodec()];
  [channel sendMessage:@[arg_device] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)setBluetoothEnabledStatusEnabled:(NSNumber *)arg_enabled completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.ChatMessageFlutterApi.setBluetoothEnabledStatus"
      binaryMessenger:self.binaryMessenger
      codec:ChatMessageFlutterApiGetCodec()];
  [channel sendMessage:@[arg_enabled] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)setBluetoothAvailableStatusEnabled:(NSNumber *)arg_enabled completion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.ChatMessageFlutterApi.setBluetoothAvailableStatus"
      binaryMessenger:self.binaryMessenger
      codec:ChatMessageFlutterApiGetCodec()];
  [channel sendMessage:@[arg_enabled] reply:^(id reply) {
    completion(nil);
  }];
}
@end
