// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, DeviceBondState) {
  DeviceBondStateNone = 0,
  DeviceBondStateBonding = 1,
  DeviceBondStateBonded = 2,
};

@class Message;
@class Device;

@interface Message : NSObject
@property(nonatomic, copy, nullable) NSString * text;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * author;
@end

@interface Device : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSArray<NSString *> * uuids;
@property(nonatomic, copy, nullable) NSString * macAddress;
@property(nonatomic, assign) DeviceBondState bondState;
@end

/// The codec used by ChatMessageHostApi.
NSObject<FlutterMessageCodec> *ChatMessageHostApiGetCodec(void);

@protocol ChatMessageHostApi
- (void)connectId:(NSString *)id error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disconnectWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)sendMessageAuthorId:(NSString *)authorId message:(Message *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSArray<Device *> *)pairedDevicesWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)discoverDevicesWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)isBluetoothEnabledWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)isBluetoothAvailableWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)enableBluetoothWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ChatMessageHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ChatMessageHostApi> *_Nullable api);

/// The codec used by ChatMessageFlutterApi.
NSObject<FlutterMessageCodec> *ChatMessageFlutterApiGetCodec(void);

@interface ChatMessageFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)putMessageMessage:(Message *)message completion:(void(^)(NSError *_Nullable))completion;
- (void)putNewDeviceDevice:(Device *)device completion:(void(^)(NSError *_Nullable))completion;
- (void)setBluetoothEnabledStatusEnabled:(NSNumber *)enabled completion:(void(^)(NSError *_Nullable))completion;
- (void)setBluetoothAvailableStatusEnabled:(NSNumber *)enabled completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
