// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Message;

@interface Message : NSObject
@property(nonatomic, copy, nullable) NSString * text;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * author;
@end

/// The codec used by MessageHostApi.
NSObject<FlutterMessageCodec> *MessageHostApiGetCodec(void);

@protocol MessageHostApi
- (void)subscribeOnMessagesAuthorId:(NSString *)authorId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)sendMessageAuthorId:(NSString *)authorId message:(Message *)message error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void MessageHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessageHostApi> *_Nullable api);

/// The codec used by MessageFlutterApi.
NSObject<FlutterMessageCodec> *MessageFlutterApiGetCodec(void);

@interface MessageFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)getMessageMessage:(Message *)message completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
